### ISSUE TITLE
questions .. works with meteor 1.0+?

### ISSUE THREAD

**Issue by newgeekorder** [ajbarry/meteor-yahoo-finance#1]
Potential newb questions for a number meteor packages including this one I get "undefined" calling the Yahoo functions in client or server code?

**Comment by ajbarry** [comment]
Yes. I am using it in a Meteor 1.0.2.1 app just fine. The library isn't yet exposed to the client however as I only needed it to do some server-side queries and cache the quote data on my models.

Do you need to get quote from your clients? It probably isn't a ton of work for me to implement.

**Comment by newgeekorder** [comment]
yes it was a noob question ... I'm now have an observe pattern with high charts pulling data from the server and reacting to mongo changes. Many thanks
