### ISSUE TITLE
YahooFinance is not defined when trying to access on client/main.js

### ISSUE THREAD

**Issue by kidsil** [ajbarry/meteor-yahoo-finance#2]
I'm trying to have a helper that returns a snapshot:
`YahooFinance.snapshot({symbol:'GOOG'});`

I'm getting an error:
`ReferenceError: YahooFinance is not defined`

There's obviously something I'm missing here.... ?

**Comment by kidsil** [comment]
Never mind, wasn't aware this is a server side thing, just used methods to make that information available to the client.

**Comment by ajbarry** [comment]
Hey @kidsil sorry I didn't get back to you sooner. But yeah, for my purposes I am dropping quote data on my models server-side. I really should make this universal tho. You're not the first to stumble on client-side use. Yahoo would probably like you better if your clients were the consumers anyway ;-)

**Comment by kidsil** [comment]
hey @ajbarry that's no problem.
I forked the repo to update the node-yahoo-finance dependency, as I was missing a much needed single snapshot quote.
I've also updated the tests (and added a new one for single snapshot quote), as they were giving me a hard time with timezones (took way too long to figure that one out), all are passing now.
