### ISSUE TITLE
Certain Fields Don't return in the object.

### ISSUE THREAD

**Issue by ghost** [ajbarry/meteor-yahoo-finance#3]
The field 'j2' doesn't seem to output in the console.log(result) object. But the other ones do. So I am not quite sure why that is, it is in the fields.js file in the node package.

Client Side

`Template.stock.rendered = function (){
    if ( _.isEmpty(Session.get('ENW.V')) ) {
        Meteor.call('getQuote', 'ENW.V', function(err, result) {
            Session.set('ENW.V', result['ENW.V']);
            console.log(result);
        });
    }
}

Template.stock.helpers({
    stock: function() {
        return Session.get('ENW.V');
    }
})`

Server Side

`Meteor.methods({
  getQuote: function( stockname ) {
    return YahooFinance.snapshot({symbols: [stockname] , fields:['n','a','b','b4','j2'] });
  }
});`

**Comment by ajbarry** [comment]
Hey @kitsondevelopment, very few fields are guaranteed to contain a value for all stocks that you'll want to query. It may just be that yahoo does not have access to 'Shares Outstanding' for this particular exchange or stock.

**Comment by ajbarry** [comment]
Please let me know if there is anything further I can help you with.
